### ISSUE TITLE
Might want to add an `id` field to each model?

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/nyt-ap-elections#102]
Auto-incrementing or something? Or UUID? Many ORMs require this and it's trivial to add.

OR

We could use one of the existing fields as an ID.

**Comment by eads** [comment]
I like the latter option but don't have a strong opinion -- numeric serial ID could cause some issues if people rely on it and they change. This is a good idea though.

**Comment by jeremyjbowers** [comment]
Think I'm going to isolate whatever is the unique id for each of these
objects and decorate them with an id field representing that value.

e.g., candidates == unique_id, race == raceid, etc.


contact([{ "twitter": "@jeremybowers", "phone": "727-667-0510", "github": "
http://github.com/jeremyjbowers" }])

**Comment by eads** [comment]
awesome

On Thu, Nov 19, 2015 at 3:33 PM, Jeremy Bowers <notifications@github.com>
wrote:

> Think I'm going to isolate whatever is the unique id for each of these
> objects and decorate them with an id field representing that value.
>
> e.g., candidates == unique_id, race == raceid, etc.
>
>
> contact([{ "twitter": "@jeremybowers", "phone": "727-667-0510", "github":
> "
> http://github.com/jeremyjbowers" }])
>
> On Thu, Nov 19, 2015 at 3:28 PM, David Eads <notifications@github.com>
> wrote:
>
> > I like the latter option but don't have a strong opinion -- numeric
> serial
> > ID could cause some issues if people rely on it and they change. This is
> a
> > good idea though.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/newsdev/nyt-ap-elections/issues/102#issuecomment-158188383
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/nyt-ap-elections/issues/102#issuecomment-158189537>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by jeremyjbowers** [comment]
Closed by #24b1b28db8751bda14f0ddd7c1ba8ef34b3c08a3.
