### ISSUE TITLE
National level results

### ISSUE THREAD

**Issue by wmandrews** [newsdev/nyt-ap-elections#108]
For president, it would be nice to have `level: national` available for rollups.

**Comment by jeremyjbowers** [comment]
There's not really actually a `level=national` even for presidential -- wouldn't that just be the sum of the states?

**Comment by jeremyjbowers** [comment]
Would we really want to special case a single race like this in the importer? Feels like something we could do in the API pretty easily.

**Comment by wmandrews** [comment]
Sure, just throwing it out there.
