### ISSUE TITLE
Confab w/ Eads 11/24

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/nyt-ap-elections#119]
Should talk through a handful of things, notably:
### Logging
- [x] Where should logging config live? In this module or in `ap-elections-loader`?
- [x] Does the CLI allow logging to bubble up to the console?
- [x] What should the defaults look like? What should the user have to configure?

### New England
- [x] Can we avoid a second API call? AP townships include the FIPS of their parent county.
- [x] How terrified are we of doing math? Are tests sufficient?

### Names
- [x]  `ap-elex` or `elex`?
- [x] Can we give nicer names to various releases, e.g., `Release 0.0.45 Payne` or something?
- [x] What should we call ballot positions? Ballot issues? Ballot measures?
- [x] What should we call BaseObject? APElection? Is it even required as we cleanup performance?

### Misc
- [x] JSON schema validation?
- [x] Add timing info on the load, e.g., `download: 4.1 seconds, parse: 1.25 seconds, insert 2.0 seconds`
- [x] Format for recordings? Module for reading recordings?

**Comment by eads** [comment]
Another question related to performance: could we always cache responses
from the AP and make HEAD requests to see if cache is busted? It won't
improve processing performance but would let us increase polling frequency.

If we also cache parsed output (e.g. by pickling), you could basically call
commands as often as you wanted. There's potentially some tricky details to
that (do we then need a PID check built into the CLI execution cycle?). but
that's a way of getting around slow response times in unnatural ways.

Another question around reporting level is how that gets specified in CLI.

**Comment by jeremyjbowers** [comment]
* Log to stderr and everything will be fine.
* Logging levels with cement and configuration.
* David will take the logging tickets.
* Math is sufficient.
* Make fewer API calls.
* `elex`
* `BallotMeasure`
* `APElection`
* Look into a JSON linter to make sure the JSON response is proper, valid JSON. Make it a C lib if possible.
* No timing info, we can profile this separately if we really need to.
