### ISSUE TITLE
talk with AP about polID

### ISSUE THREAD

**Issue by eads** [newsdev/nyt-ap-elections#21]

**Comment by jeremyjbowers** [comment]
Sent an email to Tracy just now re: this.

**Comment by jeremyjbowers** [comment]
Need to get some more clarity. Will email again.

**Comment by jeremyjbowers** [comment]
Emailed again just now.

**Comment by jeremyjbowers** [comment]
## polid
Unique across all races. But not assigned to non-national politicians.

## polnum
Unique across all races in a state.

## candidateid
Only unique to a single race, e.g., not unique.

**Comment by jeremyjbowers** [comment]
Wow, this means we're using `Candidate.candidateid` improperly. Should be using polnum or polid (if it exists).

**Comment by jeremyjbowers** [comment]
Closing; have #42 as the continuation of this ticket.
