### ISSUE TITLE
Parsing functions aren't modular enough (to test)

### ISSUE THREAD

**Issue by livlab** [newsdev/nyt-ap-elections#29]
Given a JSON dump, we should have a function that can pull:
* candidates
* ballot issue
* reporting units
* candidate results 

We don't have the discrete functions to test with.

**Comment by jeremyjbowers** [comment]
This is blocking most of the testing bits. I'll knock this out ASAP.

**Comment by eads** [comment]
Excellent! I won't have time today to tackle this; getting my shit together
for next week.

On Fri, Nov 6, 2015 at 10:15 AM, Jeremy Bowers <notifications@github.com>
wrote:

> This is blocking most of the testing bits. I'll knock this out ASAP.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/nyt-ap-elections/issues/29#issuecomment-154434719>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by jeremyjbowers** [comment]
UGH THIS IS HARD I HATE EVERYTHING.

It's going to be okay.

**Comment by eads** [comment]
lol don't fear man, we can do some of this work next week when we're
pairing.

**Comment by jeremyjbowers** [comment]
Election
    Race ---------------> CandidateRace ----------> Candidate
ReportingUnit ---> CandidateReportingUnit ---> Candidate

**Comment by jeremyjbowers** [comment]
CandidateRace doesn't need to exist -- there's a CandidateReportingUnit for the highest-level unit, e.g., `level` != `subunit`.

**Comment by jeremyjbowers** [comment]
Got this in sha 619155649eedbf6493fd5b9712b436a0e109a7d9
