### ISSUE TITLE
Make fake JSON with example varied races

### ISSUE THREAD

**Issue by livlab** [newsdev/nyt-ap-elections#31]

**Comment by livlab** [comment]
Sample JSON is meant to show a variety of results combinations. It contains:

* 15 races
* numbered 00001-00015
* all types
* all levels
* real FIPSCode, polNum
* fake everything else

(The structure is a copy of test API data available 20151102.) Remember that a candidate is just "a thing on the ballot" so could be a person (with a first/last name) or a measure (in favor/against indicated in first/last name fields. Because, reasons).

Note: I noted that the sample data I used to make this had two-letter party codes even thought the API documentation shows all as 3-letter abbreviations. ¯\_(ツ)_/¯

**Comment by livlab** [comment]
Things we don't know:

* When a race is called and "winner" is added under candidate (X for win, R for runoff advance, N for race call reversal), does the other candidate get the "winner" attribute? Y/N, if Y, does it come empty? Does it come with a zero?

**Comment by livlab** [comment]
Things we now know:

* "party" field for Ballot Issues use Yes or No values to match "last" field, whereas elections for people have an actual party code under "party". This is another way to tell the difference between the two types of possible "candidate".

I used IATA US airport codes for parties in this JSON.

**Comment by livlab** [comment]
Things we now know:

* Visual survey of the sample API data shows that ballot measures always have NO vote presented before YES vote (and the ballotOrder attribute defining how they should be used), but since it's so consistent it seems it would be easy to ignore ballotOrder and either presume NO/YES default (probably bad!) or better, determine your own criteria.

**Comment by jeremyjbowers** [comment]
Killer. I'll check this into the repo shortly.
