### ISSUE TITLE
There is no way to link candidates back to races in current data

### ISSUE THREAD

**Issue by eads** [newsdev/nyt-ap-elections#43]
candidates don't have an identifier to join back to races or reporting units; meanwhile, races and reporting units can be joined on raceid

**Comment by jeremyjbowers** [comment]
This is a problem because a candidate can be in multiple races. Having a single race per candidate would actually be a CandidateRace object?

**Comment by jeremyjbowers** [comment]
You can do it through a CandidateReportingUnit which has both the candidate IDs and the race IDs. But this is probably, uh, wacky.

**Comment by eads** [comment]
CandidateReportingUnit doesn't seem like the right way to go -- that's all flattened and denormalized anyway. Maybe a CandidateRace object that can be joined through.

**Comment by jeremyjbowers** [comment]
Well, there's not a CandidateRace because CandidateReportingUnit where level != subunit is effectively the Candidate's performance in a single race.

**Comment by jeremyjbowers** [comment]
(usually, it's something like `CandidateReportingUnit.level == 'state'`but really just whatever it is that **isn't** `subunit`.

**Comment by jeremyjbowers** [comment]
Closing this -- denormalized fields and level = 'state' should solve this problem.
