### ISSUE TITLE
should election data objects have a serialize method?

### ISSUE THREAD

**Issue by eads** [newsdev/nyt-ap-elections#46]
they'll probably need a serialize() and serialize_flat() method (e.g. without hierarchy, to support CSV), unless we assume all serialization should be flat.

**Comment by jeremyjbowers** [comment]
They are all flat ATM -- unless they shouldn't be?

**Comment by jeremyjbowers** [comment]
(also agree)

**Comment by eads** [comment]
hmm, iirc races and at least one other aren't flat... lemme check

**Comment by eads** [comment]
ah, you changed it! huzzah

**Comment by eads** [comment]
hmmm, so what does this mean in the race object?

```
        self.candidates = []
        self.reportingunits = []
```

**Comment by jeremyjbowers** [comment]
While being processed, those remain nested. Once the process is finished
(eg the loop completes for this race) it removes those arrays. We can talk
in more detail tomorrow!

On Wednesday, November 11, 2015, David Eads <notifications@github.com>
wrote:

> hmmm, so what does this mean in the race object?
>
>         self.candidates = []
>         self.reportingunits = []
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/nyt-ap-elections/issues/46#issuecomment-155926331>
> .
>


-- 

contact([{ "twitter": "@jeremybowers", "phone": "727-667-0510", "github": "
http://github.com/jeremyjbowers" }])

**Comment by eads** [comment]
I don't think we need this -- thought it might be helpful for json serialization in the cli app but now I'm taking a different tack
