### ISSUE TITLE
re-factor main data objects

### ISSUE THREAD

**Issue by eads** [newsdev/nyt-ap-elections#49]
Some of the logic would be better off abstracted. e.g.:

```python
races, reporting_units, candidate_reporting_units = election.get_units(race_objs)
```

It would be nice if the magic happened behind the scenes, and you could just do:

```python
races = election.races
```

**Comment by jeremyjbowers** [comment]
Hmm. Would you also do `election.reporting_units` and `election.candidate_reporting_units` ?

**Comment by eads** [comment]
right. I think the current interface is a little messy this way -- some of the complexity of the single loops, etc, could be worked around

**Comment by eads** [comment]
I'll play around with some tweaks along these lines in a branch.

**Comment by jeremyjbowers** [comment]
I totally trust you with this.

**Comment by eads** [comment]
I'll do it in a branch anyway :D

On Wed, Nov 11, 2015 at 2:35 PM, Jeremy Bowers <notifications@github.com>
wrote:

> I totally trust you with this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/nyt-ap-elections/issues/49#issuecomment-155888025>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
