### ISSUE TITLE
catch missing AP_API_KEY environment variable 

### ISSUE THREAD

**Issue by eads** [newsdev/nyt-ap-elections#79]

**Comment by jeremyjbowers** [comment]
Returns a `KeyError`
![screen shot 2015-11-20 at 3 04 25 pm](https://cloud.githubusercontent.com/assets/109988/11310483/040d757e-8f98-11e5-933d-e8c9090258d1.png)
 now, which is good.

**Comment by eads** [comment]
Aw yeaaah!

On Fri, Nov 20, 2015 at 3:04 PM, Jeremy Bowers <notifications@github.com>
wrote:

> Closed #79 <https://github.com/newsdev/nyt-ap-elections/issues/79>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/nyt-ap-elections/issues/79#event-470799257>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
