### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by eads** [newsdev/nyt-ap-elections#96]
I think it should be "Copyright New York Times and NPR" 

I think it should be MIT. Maybe. 

@jeremyjbowers whaddya think?

**Comment by jeremyjbowers** [comment]
Our lawyers have approved Apache 2.0. I have no desire to get them involved.

**Comment by eads** [comment]
Apache 2.0 sounds great to me!

On Thu, Nov 19, 2015 at 12:09 PM, Jeremy Bowers <notifications@github.com>
wrote:

> Our lawyers have approved Apache 2.0. I have no desire to get them
> involved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/nyt-ap-elections/issues/96#issuecomment-158121321>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by jeremyjbowers** [comment]
Fix here: 5a48456444befcc2d073b8c5cf8216c6329bf8f5
