### ISSUE TITLE
write recording to disk instead of mongodb

### ISSUE THREAD

**Issue by eads** [newsdev/nyt-ap-elections#97]
Would let us drop a ton of dependencies, probably somewhat slower than mongo.

@jeremyjbowers

**Comment by jeremyjbowers** [comment]
There's an option to do that already! `export ELEX_RECORDING=flat` will write timestamped files to `/tmp/` by default or to `ELEX_RECORDING_DIR`.

**Comment by jeremyjbowers** [comment]
But I'd prefer if we kept mongodb as an option -- it's really important for us, for example, since we use hosted mongo and this needs to be accessible to a bunch of other people.

**Comment by eads** [comment]
Nice! That's lovely.

On Thu, Nov 19, 2015 at 11:46 AM, Jeremy Bowers <notifications@github.com>
wrote:

> But I'd prefer if we kept mongodb as an option -- it's really important
> for us, for example, since we use hosted mongo and this needs to be
> accessible to a bunch of other people.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/nyt-ap-elections/issues/97#issuecomment-158114618>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
